### PR TITLE
fix: Better support for `.vue`. and `.svelte` files using `jscodeshift-adapters`

### LINKED ISSUE #70: Handle `.svelte` files correctly
Initially, we included `.svelte` files by default when running migr8. In #69 I disabled including Svelte files by default because we got the feedback that HTML inside svelte files was incorrectly transformed by jscodeshift (e.g. #68). Due to time reasons we opted to temporarily ignore svelte files by default but long-term, we should find a  better way to leave HTML untouched and really only transform the script part of svelte files.

### PR DESCRIPTION
**Pull request by fnimick**
Resolves #70

### CODE REVIEW

**Review by Lms24 — COMMENTED** [review]
Hey @fnimick thanks for opening this PR and thanks for going through the trouble of publishing this library! I had a quick look at the source code and think the idea of using the framework-specific tools to parse and extract scripts is generally good! 

To be transparent, we're a bit hesitant about adding new dependencies to our tools, so before merging this PR in, I'll bring it up with the team to ensure we're on the same page.

Also, just to confirm: The diffs look a bit wild, the general pattern for the changes is:

1. remove `wrapJscodeshift` calls
2. replace with `adapt` calls
3. remove any resulting unnecessary variables (like `fileName`) 

The rest is just auto-formatting, right?

**Comment by Lms24** [comment]
Also, just as a heads-up: I'm assigning myself to this issue to track internally that I'm reviewing it. No worries though, I'm not gonna take over or anything. Happy to let you continue if we need to make further changes.

**Comment by fnimick** [comment]
@Lms24 yep, that's all I did. There was one other incredibly minor change to make typescript happy (adding an optional chain) but I will flag that for you specifically.

If you want an easier diff, turn 'ignore whitespace' on, which will hide all the lines where the only changes was the indentation from removing the `wrapJscodeshift` callback wrapper.

**Review by Lms24 — APPROVED** [review]
Man I had no idea about "Hide Whitespaces" thanks a lot for the hint!

As for this change, I'm gonna make the call and say adding the dependency is okay. Given the change is well isolated in this PR, we could (not saying we will) easily revert if we received bug reports.

Thanks for contributing, I'll make sure you're mentioned in the changelog :)

**Pull request merged**
